name: mtr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - mkl<2024.1
  - intel-openmp<2024.1
  - pip
  - pip:
      - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
      - tensorflow==2.17.0
      - numpy<2
      - matplotlib==3.7.0
      - pandas==2.0.3
      - scikit-learn==1.6.1
      - future==1.0.0
      - graphtools==1.5.3
      - joblib==1.4.2
      - meld==1.0.2
      - pygsp==0.5.1
      - scprep==1.2.3
      - tasklogger==1.2.0
      - pytz==2025.1
      - threadpoolctl==3.6.0