name: mtr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py311h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - astroid=3.3.8=py311h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - blas=1.0=openblas
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.1.31=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py311h06a4308_0
  - dill=0.3.8=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_2
  - filelock=3.13.1=py311h06a4308_0
  - flatbuffers=24.3.25=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.12.0=py311h06a4308_0
  - gast=0.5.3=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.62.2=py311h6a678d5_0
  - h5py=3.12.1=py311h5842655_1
  - harfbuzz=10.2.0=hf296adc_0
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - ipython=8.30.0=py311h06a4308_0
  - isort=5.13.2=py311h06a4308_1
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.5=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - keras=3.6.0=py311h06a4308_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.5.1=hffd6297_1
  - libtorch=2.5.1=cpu_openblas_hd25709d_2
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py311h06a4308_0
  - ml_dtypes=0.4.0=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=8.4.0=h29a9f33_1
  - namex=0.0.7=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py311h06a4308_0
  - nomkl=3.0=0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.26.0=py311h06a4308_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.12.1=py311hdb19cb5_0
  - packaging=24.2=py311h06a4308_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py311he36ed58_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.12.1=py311h06a4308_0
  - pygments=2.15.1=py311h06a4308_1
  - pylint=3.3.3=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=6.7.1=py311h6a678d5_0
  - pyqt6-sip=13.9.1=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-flatbuffers=24.3.25=py311h06a4308_0
  - pytorch=2.5.1=cpu_openblas_py311ha613aac_2
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - rich=13.9.4=py311h06a4308_0
  - scipy=1.15.1=py311h24aa872_0
  - setuptools=72.1.0=py311h06a4308_0
  - sip=6.10.0=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py311h06a4308_1
  - tensorboard=2.17.0=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - tensorflow=2.17.0=cpu_py311hbca4264_0
  - tensorflow-base=2.17.0=cpu_py311hb07566e_0
  - tensorflow-estimator=2.17.0=cpu_py311hfedf350_0
  - termcolor=2.1.0=py311h06a4308_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h39e8969_0
  - tomlkit=0.13.2=py311h06a4308_0
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - urllib3=2.3.0=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=3.1.3=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - wrapt=1.17.0=py311h5eee18b_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - future==1.0.0
    - graphtools==1.5.3
    - joblib==1.4.2
    - matplotlib==3.7.0
    - meld==1.0.2
    - pandas==2.0.3
    - pygsp==0.5.1
    - pytz==2025.1
    - scikit-learn==1.6.1
    - scprep==1.2.3
    - tasklogger==1.2.0
    - threadpoolctl==3.6.0
    - tzdata==2025.1
prefix: /home/karthik/miniconda3/envs/mtr
